services:
  code-server:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - "$HOME/.config:/home/coder/.config"
      - "~/workspace/${PORT}:/home/coder/project"
    environment:
      - DOCKER_USER=$USER
      - USER=$USER
    command: code-server
  
  localstack:
    container_name: localstack_${PORT}
    image: localstack/localstack
    ports:
      - "${LOCAL_STACK_EDGE_PORT}:4566"
    environment:
      - SERVICES=iam,lambda,apigateway
      - DEBUG=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=${LOCAL_STACK_EDGE_PORT}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"