services:
  code-server:
    container_name: codeserver-${PORT}
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - "$HOME/.config:/home/coder/.config"
      - "~/workspace/${PORT}:/home/coder/project"
    environment:
      - DOCKER_USER=$USER
      - USER=$USER
      - LOCALSTACK_HOST=localstack-${PORT}
    command: code-server && cd /home/coder/project/test-driving-lambdas && npm i
  
  localstack:
    container_name: localstack-${PORT}
    image: localstack/localstack
    ports:
      - "${LOCAL_STACK_EDGE_PORT}:4566"
    environment:
      - SERVICES=iam,lambda,apigateway
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localstack-${PORT}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=${LOCAL_STACK_EDGE_PORT}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"